---
spring:
    h2:
        console.enabled: true
    jpa:
        database: POSTGRESQL
        show-sql: false
        hibernate:
            ddl-auto: none
    database:
        driverClassName: org.postgresql.Driver
    datasource:
        platform: postgres
        url: jdbc:postgresql://127.0.0.1:5432/postgres
        username: postgres
        password: postgres
        tomcat:
            max-active: 10
            initial-size: 5
            test-on-borrow: true
            validation-query: select 1

liquibase:
  default-schema: postgres